### ISSUE TITLE
It this fork of flutter_secure_storage?

### ISSUE THREAD

**Issue by apiep** [koji-1009/flutter_secure_storage#33]
As the title said, is this a fork of flutter_secure_storage but with security issue fixed?

As I am in need of another kind secure storage for flutter, but did not know about security stuff and it seems like this [issue](https://github.com/mogol/flutter_secure_storage/issues/769) will not be merged soon

**Comment by koji-1009** [comment]
Yes, this repository is a fork of flutter_secure_storage.

---

The referenced issue means that EncryptedSharedPreferences is deprecated. If you have not enabled the EncryptedSharedPreferences option for Android and have set your app's min support sdk to 23 or higher, then you should not have any major issues.

Technically, there are several technical challenges to re-encrypt from EncryptedSharedPreferences to KeyStore+SharedPreferences. This repository, the issue is avoided by adding a migrate option from EncryptedSharedPreferences to DataStore. See https://github.com/koji-1009/flutter_secure_storage/tree/main/flutter_secure_storage_x#important-notice-for-android.
